# Generated by Django 2.2.5 on 2020-02-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_order_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='menu',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='menu_order_app.Menu'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='menu_order_app.Order'),
        ),
    ]
